### ISSUE TITLE
Support for GDscript

### ISSUE THREAD

**Issue by mathewcst** [BeardedBear/bearded-theme#101]
By default the theme doesn't support some GDscript keywords/tokens. Mostly the `class_name` and `extends` keywords were bugging me out.

I changed manually on my `User Settings` and here's the snippet:

```JSON
"editor.tokenColorCustomizations": {
    "[Bearded Theme Arc]": {
      "textMateRules": [
        {
          //CLASS_NAME
          "scope": ["keyword.language.gdscript"],
          "settings": {
            "foreground": "#F38CEC",
            "fontStyle": "italic"
          }
        },
        {
          //PLAYER
          "scope": ["entity.name.type.class.gdscript"],
          "settings": {
            "foreground": "#ff7085"
          }
        },
        {
          //CONSTS
          "scope": ["constant.language.gdscript"],
          "settings": {
            "foreground": "#ABB7C1",
            "fontStyle": "bold"
          }
        }
      ]
    }
  },
  ```
  
  Here's some screenshots:
  
### BEFORE
![image](https://user-images.githubusercontent.com/5620645/212158833-2947d760-776b-4de0-9d9c-5d979c6a2d5c.png)
![image](https://user-images.githubusercontent.com/5620645/212160372-70210f2e-0421-4ae6-b7a6-c0bacbbb7371.png)

### AFTER
![image](https://user-images.githubusercontent.com/5620645/212159868-6dc72cde-dd58-4821-a9f5-ba145e007cf1.png)
![image](https://user-images.githubusercontent.com/5620645/212160399-e4f19e33-3345-4b5f-8735-9baafff29aee.png)

Idk maybe the author could use these scopes to add (or not) support for the official theme. 

That's all xD

**Comment by BeardedBear** [comment]
I tried to do what I could to make the colours match the other languages as much as possible, but the scopes are very very limited unfortunately...
