### ISSUE TITLE
Editor Tooltip Wrong Color

### ISSUE THREAD

**Issue by k86td** [BeardedBear/bearded-theme#103]
I was testing with the dark themes (ex: Black Gold), and the editor tooltip window wasn't displaying the text since it was the same color as the background. It should have a editor tooltip color lighter than the actual background.

I'm not sure about the other themes, but I've tested some arcs ones and they all shared the same issue.

This is on VS Community/Enterprise 2022.

**Comment by BeardedBear** [comment]
"VS Community/Enterprise 2022" ??? how could you test the theme on it, I only created this theme for Visual Studio Code, not Visual Studio

**Comment by k86td** [comment]
Oh man, I guess they're importing extensions from code then. I found it [here](https://marketplace.visualstudio.com/items?itemName=Daomtthuan.BeardedTheme).

For sure it's not working lol. Sorry about that.

**Comment by BeardedBear** [comment]
No problem, I did not know that some people had created ports of my theme for Visual Studio, thank you for making me discover them, I asked them to prevent in a more obvious way that they were not official versions!

**Comment by k86td** [comment]
I mean it's pretty straightforward, I didn't see it. Great themes btw, I'll close this issue since it's already written they're based on your repo!
Thank you.
