### ISSUE TITLE
Theme just changed color

### ISSUE THREAD

**Issue by Code-Blooded1** [BeardedBear/bearded-theme#106]
Emerald theme colors got changed suddenly !!!

**Comment by GilYairYamin** [comment]
I believe the colours changed in all "black & gem" themes, because I experience the same issue with Black and Gold.
Maybe it is due to the contrast fix that happened a week ago?

Can you estimate how long it will take to fix?

**Comment by BeardedBear** [comment]
It's already fixed for version 8 on the master branch, which should be ready in a few days, there is a lot of refactoring :)

**Comment by GilYairYamin** [comment]
For the time being you can install a previous version on your VS-Code if you want the previous colours.
Just google how to install a specific version of an extension in VS-Code.

**Comment by BeardedBear** [comment]
The V8.0.0 of the extension is now available, with the revert for Black and Gems colors ;).

FYI the changelog: 

### Enhancements

- Complete refactorisation for building UI colors (some variations may have some small differences from previous versions, but they are now all based on the same foundation, and creating new variations will now be much easier to do)
- All focus and hover background color for menus and quickmenus are now consistents
- All foreground color for menus and quickmenus are now consistents
- Better order for brackets color pairing

### Fixes

- Fix ruler color for light variations
