### ISSUE TITLE
PHP variables are shown incorrectly

### ISSUE THREAD

**Issue by ptyskju** [BeardedBear/bearded-theme#107]
In PHP files, only part of variable is highlighted. `$` sign is always dimmed like comment.

![image](https://user-images.githubusercontent.com/24554387/229462656-770258e9-082a-43a9-88b3-fd8ea5836240.png)

That behavior is in all theme variations.

**Comment by kmukhamadulloev** [comment]
> In PHP files, only part of variable is highlighted. `$` sign is always dimmed like comment.
> 
> ![image](https://user-images.githubusercontent.com/24554387/229462656-770258e9-082a-43a9-88b3-fd8ea5836240.png)
> 
> That behavior is in all theme variations.

did you find any solution?

**Comment by BeardedBear** [comment]
yep, it will be fixed in 8.1 version :)

**Comment by BeardedBear** [comment]
Done :)
