### ISSUE TITLE
Keyboard shortcut indicators in command palette not displaying

### ISSUE THREAD

**Issue by plttn** [BeardedBear/bearded-theme#109]
Hi there! 

I just noticed that the keyboard shortcut indicators in the command palette are no longer displaying if the row isn't selected:

![CleanShot 2023-04-19 at 08 42 07](https://user-images.githubusercontent.com/7369280/233128717-6c2ca300-80c0-4821-830c-ccf7999eb46c.png)

Only the currently selected row shows the text. This seems to affect all themes, other than the newly added Milkshake ones.

**Comment by BeardedBear** [comment]
Oops ! I'll fix it as soon as possible, thanks!

**Comment by BeardedBear** [comment]
Done ! Thanks !
