### ISSUE TITLE
Powershell: Auto generated variables are not correctly marked

### ISSUE THREAD

**Issue by dt-flo** [BeardedBear/bearded-theme#111]
Hello,

apparently for powershell, automatic variables built into powershell are not correctly marked but instead they are just white. Test variable is "$matches". See screenshot:
![Screenshot 2023-05-30 184452](https://github.com/BeardedBear/bearded-theme/assets/25205082/8efded1d-f3c9-4a8f-a205-e06cdf52a845)

As you can see at the bottom, $matches is just white.

**Comment by dt-flo** [comment]
![Screenshot 2023-05-30 195647](https://github.com/BeardedBear/bearded-theme/assets/25205082/8802f5ed-6485-4308-8bf0-fc823a003f2c)
Furthermore `$?` is not correctly marked

**Comment by dt-flo** [comment]
![Screenshot 2023-05-30 201437](https://github.com/BeardedBear/bearded-theme/assets/25205082/03ae2a3c-9d5e-434e-aba8-c82bf1d00be2)

Properties of objects are not marked in red if the object is part of an array.

**Comment by dt-flo** [comment]
![Screenshot 2023-05-30 201936](https://github.com/BeardedBear/bearded-theme/assets/25205082/880f7a50-dfc2-47c9-819c-15311432be55)

function calls are white and not blue

**Comment by BeardedBear** [comment]
some fixes will be available in the next version, but others are not possible to fix, such as 
- https://github.com/BeardedBear/bearded-theme/issues/111#issuecomment-1568867052 , scope seems not available for this specific case
- https://github.com/BeardedBear/bearded-theme/issues/111#issuecomment-1568872765 , same reason

**Comment by dt-flo** [comment]
Thank you very much!

**Comment by dt-flo** [comment]
I have to add: The "$matches" variable is still white for me (#A8ADB3)

**Comment by BeardedBear** [comment]
Fixed ! And thanks a lot for sponsoring !

**Comment by dt-flo** [comment]
> Fixed ! And thanks a lot for sponsoring !

Thanks, looks good now :)
You're welcome, you deserved the money for my favorite VS Code theme :)
