### ISSUE TITLE
Style Tag

### ISSUE THREAD

**Issue by gmurad97** [BeardedBear/bearded-theme#115]
Hello.The problem is that the style tag the first quotation mark is highlighted, but not the last quotation mark, which is why there is no substructure inside the style tag
![Снимок](https://github.com/BeardedBear/bearded-theme/assets/118082910/af207659-1ca9-4dcb-b06d-da19cccd2ee4)

**Comment by connortwiegand** [comment]
I'm having the same problem as well. This issue was brought up (and fixed) in #70, but it looks like it snuck its way back in.
