### ISSUE TITLE
CMake functions not highlighted

### ISSUE THREAD

**Issue by Nerixyz** [BeardedBear/bearded-theme#119]
I'm using the [CMake](https://marketplace.visualstudio.com/items?itemName=twxs.cmake) extension to provide grammar for CMake files.

Functions like `project`, or `target_link_libraries` aren't highlighted in the bearded themes.

**Bearded Theme**
![Code_2023-07-08_21-37-39](https://github.com/BeardedBear/bearded-theme/assets/19953266/3b4f2600-5971-46e6-9c96-3e592ccd281e)

**Dark Modern**
![Code_2023-07-08_21-39-22](https://github.com/BeardedBear/bearded-theme/assets/19953266/7c2ac479-702a-425f-ba77-fb6dd362314c)

**Comment by BeardedBear** [comment]
Thanks ! Done in 8.3.0 version :)
