### ISSUE TITLE
Anthracite's colors changed in version 2.0.1

### ISSUE THREAD

**Issue by frohikey** [BeardedBear/bearded-theme#12]
1.7.2

![image](https://user-images.githubusercontent.com/13802274/80806252-761cd380-8bba-11ea-9b1f-98ff052f0dcc.png)

2.0.1

![image](https://user-images.githubusercontent.com/13802274/80806269-803ed200-8bba-11ea-8f69-5e055f028996.png)

I'd be probably ok with fewer colors. It seems it was your intention, right? But switching a context of colors is an absolute deal-breaker for me. 

I loved this theme very much. Thank you for any statement regarding 2.X versions. The original Anthracite is not going back?

**Comment by BeardedBear** [comment]
Hello! I have completely rebuilt and simplified my theme build system, and obviously there are some misfires if I look at your screenshots.

Thank you for taking the time to show me all this, I'm going to make a fix soon, it shouldn't look like this :)

**Comment by BeardedBear** [comment]
and indeed, I intended to reduce the number of different colors :)

**Comment by BeardedBear** [comment]
I released version 2.1.0 (2.1.0 and not 2.0.2 because I had a variant available for release) which normally fixes your problems, could you confirm it?

**Comment by frohikey** [comment]
I confirm that 2.1.0 fixes my problems flawlessly. Good job and thanks for the fast fix.
