### ISSUE TITLE
Different color highlighting for ordinary `html`  elements and Custom React Components in JSX

### ISSUE THREAD

**Issue by safarli** [BeardedBear/bearded-theme#120]
It would be very good to see different color highlighting for ordinary `html`  elements and Custom React Components in `JSX` (`TSX`)

![code](https://github.com/BeardedBear/bearded-theme/assets/65605198/715a8907-4aec-4428-a1bd-abb9d0adc9ef)

---
My best theme is: **Bearded Anthracite**

**Comment by safarli** [comment]
Just like in VSCode Default theme, `One Dark Pro`, and some others.

**Comment by BeardedBear** [comment]
Thanks ! Done in 8.3.0 version :)

**Comment by dagonzalez1757** [comment]
It'd be good to have also an option to have it the previous way. I like every jxs tag to have the same color.

**Comment by BeardedBear** [comment]
> It'd be good to have also an option to have it the previous way. I like every jxs tag to have the same color.

Hello ! when I get the motivation, I'll create customization options including italics, border colors etc. so I'll make a note of that option ;)
