### ISSUE TITLE
Inactive tabs in inactive groups are brighter than in active groups

### ISSUE THREAD

**Issue by Loskir** [BeardedBear/bearded-theme#123]
<img width="285" alt="image" src="https://github.com/BeardedBear/bearded-theme/assets/21295738/140013bc-d3e2-4696-b3ee-b821c283c8e1">

Top group is active, bottom group is inactive. `package.json` is colored brighter in an inactive group, which is quite unintuitive. This behavior is consistent across all bearded themes

**Comment by BeardedBear** [comment]
Thanks ! Done in 8.3.0 version :)
