### ISSUE TITLE
Incorrect border color on drag-n-drop of Secondary Side Bar tabs

### ISSUE THREAD

**Issue by Loskir** [BeardedBear/bearded-theme#126]
https://github.com/BeardedBear/bearded-theme/assets/21295738/d8f6b445-18f7-4a91-a025-4f447b9f85df

In light themes, a light gray color is used, which is generally legible although lighter than in other light themes.
Dark themes use black which is almost completely invisible.

**Comment by BeardedBear** [comment]
Thanks ! Fixed in v8.3.1 !
