### ISSUE TITLE
Large color changes for C#

### ISSUE THREAD

**Issue by JoshuaClouse** [BeardedBear/bearded-theme#13]
(EDIT) I saw a similar issue was posted before, but I would like to say that I hope you don't reduce the colors too much! I really love how colorful it is compared to other themes. It reminds me of candy.

I was a huge fan of the really nice punchy colors from before. It's a large reason why I chose this theme. I did some custom edits to my background colors but the text highlighting has remained untouched and is strictly from Bearded Theme Blue. Here are some examples of before: 

![Screen Shot 2020-05-01 at 4 46 51 PM](https://user-images.githubusercontent.com/28413986/80849301-6c4f9c00-8bcb-11ea-96cf-58bfc39e6c15.png)
![Screen Shot 2020-05-01 at 4 47 10 PM](https://user-images.githubusercontent.com/28413986/80849308-707bb980-8bcb-11ea-8db5-4390729ed363.png)
![Screen Shot 2020-05-01 at 4 46 37 PM](https://user-images.githubusercontent.com/28413986/80849309-7376aa00-8bcb-11ea-86e7-6cc632adc582.png)

And this is how the theme currently looks:

![Screen Shot 2020-05-01 at 4 48 09 PM](https://user-images.githubusercontent.com/28413986/80849344-9ef99480-8bcb-11ea-899d-fc311539a6a0.png)
![Screen Shot 2020-05-01 at 4 48 13 PM](https://user-images.githubusercontent.com/28413986/80849346-a02ac180-8bcb-11ea-982e-4128843fe1fc.png)
![Screen Shot 2020-05-01 at 4 48 23 PM](https://user-images.githubusercontent.com/28413986/80849350-a1f48500-8bcb-11ea-8371-40336656c8f5.png)

The colors take a pretty hard nerf. Not sure if this is due to a new VS Code update or the new style update but I hope it can be reverted.

**Comment by BeardedBear** [comment]
Indeed, I was reported this problem yesterday, and I've made progress on the patch, I'll release version 2.0.2 (or version 2.1.0 if I finish the new variant) today :)

The reason is that I drastically reduced the number of scopes in my selectors, so there are some I didn't detect because I don't do C#, so I didn't have the reflex to look, my bad :(

Anyway, thank you for taking the time to tell me about it, originally I created this theme because I was challenged and because I couldn't find themes that really suited me (and also because I like to understand how things are done) and I didn't think that so many people would use it as well haha

**Comment by BeardedBear** [comment]
I released version 2.1.0 (2.1.0 and not 2.0.2 because I had a variant available for release) which normally fixes your problems, could you confirm it?

**Comment by JoshuaClouse** [comment]
I just took a look at my files and they look pretty again :). Thanks for the fix, keep up the great work!

**Comment by soloko** [comment]
This is happening with my colors as well. Across the board with JavaScript, TypeScript, HTML... etc. I had to revert back to version 1.7.2 to get the colors back.

**Comment by BeardedBear** [comment]
@soloko hi ! Sorry for that... Can you give me some examples so I can correct if necessary?

**Comment by soloko** [comment]
version 1.7.2
<img width="551" alt="version 1 7 2" src="https://user-images.githubusercontent.com/50185854/81448306-ca3c3080-9143-11ea-9fe7-6f02d6cbc851.png">

version 2.1.2
<img width="552" alt="version 2 1 2" src="https://user-images.githubusercontent.com/50185854/81448314-cc9e8a80-9143-11ea-9cbd-20956bbb4836.png">

**Comment by soloko** [comment]
Also, I love this theme! I've been so lost these past few days with the different colors lol

**Comment by BeardedBear** [comment]
Outch ! I have to fix that, HTML for example shouldn't render like that, and there's also a problem with arrows. For the const/let/var in turquoize, it's intentional, but if it becomes annoying I can go back!

Can you create a safe issue for JS/TS/HTML ? so I can fix them :)
