### ISSUE TITLE
please do it in webstorm

### ISSUE THREAD

**Issue by Hcjfgjgiti** [BeardedBear/bearded-theme#132]
I'm really looking forward to the web storm thread!

**Comment by kyleorin** [comment]
Just saw this:
https://github.com/BeardedBear/bearded-theme/issues/41

I'm guessing it's out of the question; would be great tho

**Comment by BeardedBear** [comment]
It's still planned, I need to take the time to do it, but I need to create a script that will allow me to automate the updates to avoid having to copy and paste everywhere, to keep all versions consistent! :)
