### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by JakeTheWoz** [BeardedBear/bearded-theme#138]
I use 2 themes, depending on where I am and what the illumination situation is.
It would be  nice if you could create an option  where users can save their favourites.

**Comment by BeardedBear** [comment]
Hi ! merci de ta patience, mais je n'ai pas prévu d'option comme celle ci, mais tu peux essayer des extensions comme "Theme Switch" https://marketplace.visualstudio.com/items?itemName=Fooxly.themeswitch :)
