### ISSUE TITLE
Style tag #2

### ISSUE THREAD

**Issue by gmurad97** [BeardedBear/bearded-theme#139]
Hello.The problem is that the style tag the first quotation mark is highlighted, but not the last quotation mark, which is why there is no substructure inside the style tag
![246627068-af207659-1ca9-4dcb-b06d-da19cccd2ee4](https://github.com/BeardedBear/bearded-theme/assets/118082910/2f93e3fb-da12-48ed-9edd-c675fcb79398)
Issue #115 
The problem still remains unresolved. But the themes are cool, thanks for them.
I apologize in advance for my English(google translate)

**Comment by BeardedBear** [comment]
Can you give me more context? I can't reproduce the bug on my end :/

**Comment by gmurad97** [comment]
Problem on all themes from Bearded Theme

In files such as (HTML template)
blade.php
php
html

After we open the style="" attribute inside any tag, everything except the last quote is highlighted.
That is, the first quote of the style tag is highlighted, but not the last, that is, the closing one
I don’t know whether highlighting of css parameters inside the style tag is intended (but nevertheless it is not highlighted either).
Also, what data do you need to fix this bug?

**Comment by BeardedBear** [comment]
Ok i got it, thanks !
