### ISSUE TITLE
JS/TS/HTML Colors

### ISSUE THREAD

**Issue by soloko** [BeardedBear/bearded-theme#14]
### A few things off with colors for JS, TS, HTML:
- HTML tags are part purple and blue
- Pink and green are slightly lighter
- Object dot notation and bracket notation are different colors now (not sure if that was intentional)

**Version 1.7.2**
<img width="551" alt="version-1-7-2" src="https://user-images.githubusercontent.com/50185854/81572300-a7d72c80-9368-11ea-825e-52d69d2be353.png">
**Version 2.1.2**
<img width="552" alt="version-2-1-2" src="https://user-images.githubusercontent.com/50185854/81572309-aa398680-9368-11ea-92dd-c5065f597892.png">

**Comment by BeardedBear** [comment]
Thank you very much! I'll look at it as soon as I can!

**Comment by BeardedBear** [comment]
Hey ! I've fixed some of your problems in 2.2.0 version ! Can you tell me if its ok for you ? (i keep the objects accessors in orange, because in white/lightgrey, it break the reading for me :) )
