### ISSUE TITLE
Bearded Theme Monokai Black: status bar not fully contrast

### ISSUE THREAD

**Issue by darqus** [BeardedBear/bearded-theme#146]
Bearded Theme Monokai Black: status bar not fully contrast

![Снимок экрана от 2024-02-12 00-30-27](https://github.com/BeardedBear/bearded-theme/assets/30623895/c90f96a0-5be8-408d-b434-5957677784da)

**Comment by BeardedBear** [comment]
This will be fixed in version 9 :)
