### ISSUE TITLE
There is no contrast between icon and background when item is focused in autocomplete suggestions list

### ISSUE THREAD

**Issue by rohitxdev** [BeardedBear/bearded-theme#153]
This happens only in HC themes. Look how there's no contrast between the clg icon and background when focused. It's almost invisible.
<img width="218" alt="Screenshot 2024-02-22 at 14 20 50" src="https://github.com/BeardedBear/bearded-theme/assets/66140815/0f8fd679-d564-4252-9ff8-c1d9f3e4dd4f">
<img width="223" alt="Screenshot 2024-02-22 at 14 23 00" src="https://github.com/BeardedBear/bearded-theme/assets/66140815/ef25ebf7-06fc-4e72-ab62-68f4e29ca9bc">

**Comment by BeardedBear** [comment]
Done ;)

**Comment by rohitxdev** [comment]
Wow. Fixed it in a less than a day. Thank you so much!
