### ISSUE TITLE
Change in line editorLineNumber colors

### ISSUE THREAD

**Issue by khannurien** [BeardedBear/bearded-theme#154]
Hi, first of all thanks for the hard work, I've been using your Solarized Light theme for years :-)

I noticed a change in `editorLineNumber` colors:

![image](https://github.com/BeardedBear/bearded-theme/assets/31770422/a77b6e40-ce8a-4d6d-bfe6-771609a6f838)

Originally, it looked like that (taken from the repository's screenshot):

![image](https://github.com/BeardedBear/bearded-theme/assets/31770422/4487ea7a-90e1-4422-9bd3-4af21ad7ea27)

In my opinion, the original colors were more readable. Is that a wanted change or a side effect due to changes in VSCode?

Thank you!

**Comment by BeardedBear** [comment]
Done ;)
