### ISSUE TITLE
hover color of magnifying glass icon when zoom is not visible

### ISSUE THREAD

**Issue by nerdydaemon10** [BeardedBear/bearded-theme#158]
when i-zoom vscode the magnifying glass icon at the bottom appear, when i hover it the icon not slightly visible
![image](https://github.com/BeardedBear/bearded-theme/assets/160330368/40b999d9-1193-4266-8652-e4187cddf003)

**Comment by BeardedBear** [comment]
Thanks ! Done in https://github.com/BeardedBear/bearded-theme/releases/tag/v9.1.4 :)
