### ISSUE TITLE
Missing italics

### ISSUE THREAD

**Issue by PeteLatham-CothamTechnologies** [BeardedBear/bearded-theme#16]
I've just installed version 2.2.1 but I'm not seeing italics in comments etc. Can't see any notes about needing to change any configurations etc. Ligatures are fine though.

The font I'm using is Dank Mono.

**Comment by BeardedBear** [comment]
Hello ! I don't have issues with italics, it work perfectly for me :  
![image](https://user-images.githubusercontent.com/7188702/82729228-0059e280-9cf6-11ea-8029-e6536f203741.png)
![image](https://user-images.githubusercontent.com/7188702/82729229-0e0f6800-9cf6-11ea-95ed-22c0f4b825e9.png)
![image](https://user-images.githubusercontent.com/7188702/82729238-2bdccd00-9cf6-11ea-82be-188d03d0e8f3.png)

- Do you have the same problem with other themes? 
- Do you have the same problem with other fonts?
