### ISSUE TITLE
Markdown Headers with different colors 

### ISSUE THREAD

**Issue by Nova38** [BeardedBear/bearded-theme#164]
This issue is to propose setting headers colors in markdown documents based on the heading level. I have found that this can improve the readability of the documents as it allows for quickly being able to tell the sibling headings apart from the children headings. 

I currently do this via manual adding textmaterules to change the colors in my settings, but I think that including this in the theme (and having it map to the color pallet of a given theme) would add to the already amazing theme.

Bellow is an example of applying these texmate rules in the vivid black theme:

![image](https://github.com/BeardedBear/bearded-theme/assets/17151865/48407200-3d8d-4019-b0c4-b3f5fae0c6dc)

![image](https://github.com/BeardedBear/bearded-theme/assets/17151865/1d3155b1-87f1-4740-808d-53bc8b84dc70)

```json
"textMateRules": [
      {
        "scope": "heading.1.markdown entity.name.section.markdown, heading.1.markdown punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#9cecfb"
        }
      },
      {
        "scope": "heading.2.markdown entity.name.section.markdown, heading.2.markdown punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#83a4d4"
        }
      },
      {
        "scope": "heading.3.markdown entity.name.section.markdown, heading.3.markdown punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#009f78"
        }
      },
      {
        "scope": "heading.4.markdown entity.name.section.markdown, heading.4.markdown punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#d57300"
        }
      },
      {
        "scope": "heading.5.markdown entity.name.section.markdown, heading.5.markdown punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#ff4647"
        }
      },
      {
        "scope": "heading.6.markdown entity.name.section.markdown, heading.6.markdown punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#ff3b8d"
        }
      }
    ]
```

**Comment by BeardedBear** [comment]
Hello! Thanks for suggesting this, I found it very interesting! However, I tried it on my own and didn't really like the result, I think it adds too many different colors that lose legibility when mixed with the rest of the markdown content, but good idea though!
