### ISSUE TITLE
Contrast issues in Terminal

### ISSUE THREAD

**Issue by B4T3S** [BeardedBear/bearded-theme#168]
Contrast seems to break a bit when using lighter backgrounds with light text-color in the terminal.
For example 

Using the `Monokai Black` variant: (but the issue persists across all dark color-variations)
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/a3c360f7-fa9d-4211-a4cc-bf185246d47a)

Using the `Coffe Cream` variant seems to break even more:
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/7258b6a1-65b5-43ac-a652-f9586fbd1567)

For reference, using the default `Dark` theme for VSCode:
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/58ff602e-fb8a-4c52-a0e3-40275d94f992)

A current "workaround" is just highlighting the invisible text:
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/086f6fa3-c71e-4dd6-84fc-83c048a0ffe6)

**Comment by BeardedBear** [comment]
I can't reproduce this bug, can you tell me more about how you achieve this result?

**Comment by B4T3S** [comment]
Sure thing! To reproduce, I used this command[^1]: 
```bash
echo "\n This is readable! \033[0;100m This isn't! \033[0m\033[90m"
```

Which resulted in this output:

Normal:<br>
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/4414c382-f982-4a79-8dec-b5b5df1b02ae)

With the text highlighted:<br>
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/d3a59490-8476-42e8-afb5-92f1d66d2055)

(Both times using the `Bearded Theme Ocianic`)

Switching back to `Dark (Visual Studio)` displays the text with background correctly:<br>
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/3c56c3a1-9ca3-4211-bdd6-da1efea41e2e)

[^1]: [A gist with the ANSI codes explained](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#8-16-colors)

**Comment by SyedMSawaid** [comment]
I fixed it this way,

```json
  "workbench.colorCustomizations": {
    "terminal.ansiBrightBlack": "#374151"
  },
```

this is what it looks like right now

![image](https://github.com/BeardedBear/bearded-theme/assets/34231494/f3e7a883-81f3-4a77-a51d-d7c351a37284)

---

I think the problem is with the default value for `terminal.ansiBrightBlack` which is `#c8c8d566`.

**Comment by BeardedBear** [comment]
@SyedMSawaid @B4T3S can you tell me which OS you're using, and which shell? I'm on Windows and I don't have this problem at all :/ the only thing that differs from the other terminal colors is that I use opacity. So if you don't mind, I'll provide you with a version to install locally via the extension tab (a .vsix file) so that you can try it out :/
[9.1.5-preview.zip](https://github.com/user-attachments/files/15542669/9.1.5-preview.zip)

**Comment by B4T3S** [comment]
Sure thing! The preview seems to fix the issue! </br>
(Although for some reason my terminal decided that ANSI codes aren't a thing anymore, unless they're coming from a python shell lol)
![image](https://github.com/BeardedBear/bearded-theme/assets/23524203/2f6b5ebd-b85f-45cc-985d-4d2985eca99d)

Regarding what OS and shell I use:

- Privately I'm running `Win11` with the `Git Bash` shell, so "normal" bash.
- At work I'm running `Fedora` with the `ZSH shell`

**Comment by SyedMSawaid** [comment]
@BeardedBear I was facing this issue with Windows 10 + WSL. 

I moved to Mac a couple of days ago and teared down my windows dev environment so I can't test the preview now. Sorry :/

My theory is that opacity would have some issues with WSL. When I removed the last two letters of the original `#c8c8d566` value, it started working. But the contract wasn't that great so I changed it to `#374151`.
