### ISSUE TITLE
Whitespace Rendering much too bright now

### ISSUE THREAD

**Issue by Parker8283** [BeardedBear/bearded-theme#17]
With the v3 update, the whitespace rendering color is much brighter than it used to be. It can be distracting, especially in comments. See an example below (using the Blue variant). I don't have an image of what it was before, but if that's needed let me know.

VSCode: 1.45.1
BeardedTheme: 3.0.0

![Example](https://i.imgur.com/4FWJA6n.png)

**Comment by BeardedBear** [comment]
Thanks for the feedback !

I released version 3.0.1 in order to fix this problem and as I noticed that you were using Pair Bracket Colorizer, I took the opportunity to add in the Readme colors that correspond + to the themes if needed :)

**Comment by Parker8283** [comment]
Oh wow! Thanks! It looks great!
