### ISSUE TITLE
Squiggly underlines are displayed in the middle of the text

### ISSUE THREAD

**Issue by ale-scussel** [BeardedBear/bearded-theme#171]
Hello, with the latest  versions of both vs-code (1.88.0) and bearded-theme (v9.1.4), the squiggly lines from eslint are placed just in the middle of the text and not as underline:
![image](https://github.com/BeardedBear/bearded-theme/assets/157618094/71ba7626-b3b4-4fb1-9318-e5ed746d196d)

This seems to be a theme related issue as in all other themes i tested the underline is just below the text.

**Comment by palashmon** [comment]
It's happening in other themes also like
- https://github.com/wesbos/cobalt2-vscode/issues/248
- https://github.com/catppuccin/vscode/issues/361

Also, it is reported after the recent VS Code version: Code 1.88.0 update:
- https://github.com/microsoft/vscode/issues/209614

**Comment by BeardedBear** [comment]
Hi! I don't have this problem on my side (windows 11), I have the impression that it could be a linux bug, what OS do you use? Did updating VSCode to 1.88.1 solve the problem?

**Comment by ale-scussel** [comment]
Hi! I'm indeed on linux (EndeavourOS) and unfortunately the update don't seem to have fixed the issue :(

**Comment by Spitfire1900** [comment]
I've reproduced on Windows 11 and Kubuntu. Attached are screenshots of Coffee and Dark+ on Windows 11 with v9.1.4.

![image](https://github.com/BeardedBear/bearded-theme/assets/6462596/bb71e6da-51e3-4ded-b1f7-1b5c8fc385f7)
![image](https://github.com/BeardedBear/bearded-theme/assets/6462596/7416acac-c94b-43b3-a277-8b4b93eba910)

**Comment by acramernc** [comment]
Reproduced on Windows 10 with vscode version 1.88.1
Screenshot from theme "Bearded Theme Vivid Black"

![image](https://github.com/BeardedBear/bearded-theme/assets/30380231/4fe7bbc6-9ae7-4304-8b44-d3b8e562749c)

Applying temporary fix mentioned by ale-scussel fixed the issue

![image](https://github.com/BeardedBear/bearded-theme/assets/30380231/07666ceb-a454-43a7-92c0-e8771b6b109d)

**Comment by Spitfire1900** [comment]
Same. Fixed as of code 1.89.0
