### ISSUE TITLE
[feature request] - add ability to set a beard theme in the settings.json

### ISSUE THREAD

**Issue by CalvinWilkinson** [BeardedBear/bearded-theme#173]
Hello!!

I love your extension. The themes are great!! The only thing I would really like, though, is the ability to set the theme in the settings.json file. I have a lot of projects, profiles, and languages going on, and it would be great to have this feature so it could be committed to the code base.

Unless I am missing something but when I attempted this, it was not recognized.

Cheers

**Comment by BeardedBear** [comment]
I'm afraid I don't quite understand your request, I have the feeling that it concerns a VSCode configuration rather than via my extension directly haha

**Comment by CalvinWilkinson** [comment]
@BeardedBear 

Sorry.  I should of elaborated more.

Yes.  I am talking about being able to set which theme a user wants in the vscode _**settings.json**_ configuration file.

So for example:
```json
{
	"[bearded-theme]": {
		"theme": "arc-eggplant",
	}
}
```

or something similar. This way, we don't have to keep setting it via the extension tab by clicking the _**Set Color Theme**_ button.

So instead of:
![image](https://github.com/BeardedBear/bearded-theme/assets/85414302/ca2f1c59-d9eb-45c1-bf0b-135c53d9c99e)

we could just set a setting and it would always use that theme when loading a particular project.

I don't know if that is easy or not or even worth doing.  It was just an idea.   😀

**Comment by BeardedBear** [comment]
I don't understand the difference with adding

```json
{
    "workbench.colorTheme": "Bearded Theme Aquarelle Lilac"
}
```

in `settings.json` haha

**Comment by CalvinWilkinson** [comment]
Nvm.  This is my bad.

I did not realize that you could do that.  Also, when I tried something like this in the past, it did not work. I just realized that it did not work in the past because I had a VSCode workspace and that setting does not work with workspaces.

Sorry for wasting your time.
