### ISSUE TITLE
unable to select content after collapse a range

### ISSUE THREAD

**Issue by cannot-hero** [BeardedBear/bearded-theme#174]
Unable to select the content after collapse a range.

when a range is expanded, this works
![image](https://github.com/BeardedBear/bearded-theme/assets/54719786/4f5a49dc-0975-4a13-9ab9-be7c18df1bc4)

but after collapse it, cant to select the content
![image](https://github.com/BeardedBear/bearded-theme/assets/54719786/94e325fe-484b-4a4f-8639-f3d503c11c6c)

this also happens in js document
expanded
![image](https://github.com/BeardedBear/bearded-theme/assets/54719786/deae388f-a0a5-4e74-bf99-8047848373d7)

collapsed
![image](https://github.com/BeardedBear/bearded-theme/assets/54719786/0b16a5c9-c650-4fc1-8458-ab4708e4a78b)

Is it a special design or just a bug?

**Comment by cannot-hero** [comment]
I love the theme very much, but this issue confuses me

hope  to get reply

**Comment by vinnlee** [comment]
#166

**Comment by cannot-hero** [comment]
want to know when is the next release @BeardedBear, thx!
