### ISSUE TITLE
Missing stylus syntax highlighting

### ISSUE THREAD

**Issue by lednhatkhanh** [BeardedBear/bearded-theme#18]
![image](https://user-images.githubusercontent.com/9303093/83093299-58636100-a0c9-11ea-8b85-a53f00d0ea31.png)

This screenshot is from a Vue file, but this also happens to `.styl` file

**Comment by BeardedBear** [comment]
hey ! i push an update, can you tell me if is OK for you ? :)

**Comment by lednhatkhanh** [comment]
It's working now, thank you!

![image](https://user-images.githubusercontent.com/9303093/83588533-d4532280-a57b-11ea-8b27-9b951e684148.png)

This theme is gorgeous and with stylus support, this is my daily theme now.
