### ISSUE TITLE
License Clarification: README says MIT, LICENSE file says GPL-3.0

### ISSUE THREAD

**Issue by PauloDeSousa** [BeardedBear/bearded-theme#185]
Hi,

I've noticed a discrepancy in the licensing information for this project. The [README.md](https://github.com/BeardedBear/bearded-theme/blob/master/README.md) mentions that "This theme is released under the MIT License", while the [LICENSE file](https://github.com/BeardedBear/bearded-theme/blob/master/LICENSE) states it's under the GPL-3.0 License.

Could you please clarify which license applies to this theme?

Thanks for your help!

**Comment by BeardedBear** [comment]
Thanks for pointing this out! It will be fixed in version 9.2.0, the license is GPL-3.0. :)
