### ISSUE TITLE
Backslash in Python raw strings

### ISSUE THREAD

**Issue by ueberBrot** [BeardedBear/bearded-theme#21]
I don't know if you can make it happen but the following is vexing me pretty hard.

In Python a raw string is created by prefixing a string literal with `r` or `R`. Python raw string treats backslash (`\`) as a literal character.
So the normal behavior for the highlighting of a path with backslashs (`\`) is like the following screenshot:
![image](https://user-images.githubusercontent.com/32489486/88098597-4e764f80-cb9a-11ea-99d3-b69132dc6137.png)

When you use a raw string python treats it as stated before as a literal character. The highlighting looks like this:
![image](https://user-images.githubusercontent.com/32489486/88098924-cf354b80-cb9a-11ea-99a2-5d9c5a25a2bb.png)

I know that it does what it should do for the highlighting but would it be possible to disable the highlight behavior when you use a raw python string?
It would be nice when the character after a backslash in a raw string would not be highlighted as an escaped character.

**Comment by BeardedBear** [comment]
Unfortunately, I have no control over this, it's the VSCode itself that interprets it...
I cannot dissociate it because they are considered as a single entity :(

![image](https://user-images.githubusercontent.com/7188702/88163913-a1401d80-cc13-11ea-8461-7317d5487672.png)

**Comment by ueberBrot** [comment]
That's to bad. Now I'm facing a dilema: Switch theme or don't use raw strings.

Thank you anyway.
