### ISSUE TITLE
Visual Studio Community

### ISSUE THREAD

**Issue by edwardLunaDev** [BeardedBear/bearded-theme#23]
Hellooo! I love your themes and I am an especially huge fan of black and ruby on VS Code and I was wondering if there is an extension for VS Community? I'm not sure if its been brought up already but I searched around and honestly I would just love to have that as my theme on there as well, either way thank you so much you have increased my love of staring at my editor by 1000% Awesome work!

**Comment by BeardedBear** [comment]
Hello! Thank you very much! Unfortunately, I only use VSCode, so since I initially created these themes for my own use, I didn't imagine making them for Visual Studio Community or the Jetbrains suite... But maybe one day I'll take up this challenge!

**Comment by edwardLunaDev** [comment]
Totally understandable, just thought id reach out in case you did. As I said, either way your themes are awesome! I will continue using them on VS Code and if one day they're on VS Community I'll definitely snatch them up as well!
