### ISSUE TITLE
The color of brackets and the like appears to be incorrect when editing C/C++ in recent releases

### ISSUE THREAD

**Issue by ThePC007** [BeardedBear/bearded-theme#25]
This is what the Arc Eolstorm theme* looks like in C++ in any version >= 3.2.8:
![image](https://user-images.githubusercontent.com/5817392/96374827-7ebb9300-1175-11eb-9f67-e6e8dd34aed9.png)

This is what the same piece of code looks like in version 3.2.7:
![image](https://user-images.githubusercontent.com/5817392/96374951-318bf100-1176-11eb-97a7-d38df8867351.png)

As you can tell, the brackets, equal signs, and the like are colored differently in the more recent versions. Judging by the screenshots on the Github page, the brighter, less "transparent"-looking color seems to be the intended color. Moreover, the issue does not exist when editing Javascript code. 

Therefore, I suspect this might be a bug in the theme.

I am running VS Code 1.50.1.

*The issue appears to persist across all flavors of the BeardedTheme.

**Comment by BeardedBear** [comment]
I can't reproduce the colors displayed in your captures, do you use a special extension ?

**Comment by ThePC007** [comment]
The issue still persists even after disabling all extensions safe for Bearded Theme itself:

![image](https://user-images.githubusercontent.com/5817392/96909298-24387480-149e-11eb-8f5f-9e3533069ffc.png)

This is with Bearded Theme 3.4.1 installed.
