### ISSUE TITLE
Configuration toggle for italic keywords

### ISSUE THREAD

**Issue by lyinfu** [BeardedBear/bearded-theme#26]
The default style always render keywords like ***`class`*** or ***`def`*** in italic. I think this is more C lang IDE font style. I use Python every day, and keeping these language keywords rendered in normal fonts would be good for me. Maybe consider adding this feature toggle in configuration so we can make our own decision.

BTW, really love your themes! It's amazing!

**Comment by EnderDuckLikesCoding** [comment]
Yeah, that would be great. This theme is perfect in nearly every way. The only thing that would make it better for me is if I could turn off the italics.

**Comment by Bjorn-Eric-Abr** [comment]
And a year later ... There is a "customization tool" built in to VS Code!

[This video shows you how to add TextMate Rules](https://egghead.io/lessons/vs-code-adding-custom-syntax-highlighting-to-a-theme-in-vscode). Adding an empty string to `fontStyle` will reset to the regular font variant. 

These are my italics resets: 
```JSON
"editor.tokenColorCustomizations": {
	"textMateRules": [
		{
			"scope": [
				"comment",
				"entity.other.attribute-name",
				"entity.other.inherited-class",
				"support.function",
				"variable",
			],
			"settings": {
				"fontStyle": ""
			}
		}
	]
},
```

You can scope the resets to a specific theme like this: 
```JSON
"editor.tokenColorCustomizations": {
	"[Bearded Theme Monokai Terra]": {
		"textMateRules": [
			// ... your rules
		]
	}
},
```

**Comment by aquibmastan** [comment]
Thanks for the tip! I could overwrite everything to non-italic except for properties/variables... they take their styling from semantic highlighting which apparently takes precedence. 
I love this theme but I wish there was a toggle for italics - non italic versions would also be ok. ;)
