### ISSUE TITLE
Unwanted line separators in multi-line diff

### ISSUE THREAD

**Issue by lyinfu** [BeardedBear/bearded-theme#27]
![image](https://user-images.githubusercontent.com/29242605/99019718-eb208b00-2597-11eb-9abb-65661de46333.png)

I think these line separators are unwanted. I am using theme `BeardedTheme Oceanic`, and VS code version is `1.51.1`

**Comment by BeardedBear** [comment]
Done with 3.7.2 version ! Thanks ! :D
