### ISSUE TITLE
Dart Support for the Bearded Theme

### ISSUE THREAD

**Issue by lthoma39** [BeardedBear/bearded-theme#28]
I love the extension! I've been using them for all of my school projects. It looks beautiful in Java, but when I create a Dart project all the syntax is just white and purple. 
![Capture](https://user-images.githubusercontent.com/36754529/100850649-bb073200-3449-11eb-92b9-4136ba468adf.PNG)

**Comment by lthoma39** [comment]
Sorry, this might just be a VSCode syntax highlighting issue. My apologies

**Comment by BeardedBear** [comment]
Ahah no prob

**Comment by lthoma39** [comment]
Do you know how I can make the dart syntax highlighting look more appealing like the java highlighting syntax?
