### ISSUE TITLE
Text too dark to read in git bash using ionic serve on windows 10

### ISSUE THREAD

**Issue by akashrajum** [BeardedBear/bearded-theme#34]
Hey, so some parts of the logs are dark and super hard to read in git bash using `ionic serve -l` on windows 10, I'm using Black & Emerald theme.
![image](https://user-images.githubusercontent.com/69965508/102467082-dee78c00-4075-11eb-8946-dc5f4fd30f13.png)

**Comment by BeardedBear** [comment]
Hello, thanks for the feedback ! this will be fixedin the next version (within a few hours :))

**Comment by akashrajum** [comment]
Thanks a lot! 🥳
