### ISSUE TITLE
Currently opened filename loses highlight after its content is modified

### ISSUE THREAD

**Issue by ptrwllrd** [BeardedBear/bearded-theme#35]
When you switch between opened files their respective names are highlighted in the `Open editors` section of the `File Explorer` but once you type something - the highlight disappears. It's pretty annoying when you have a bunch of files opened and lose track of which one you are currently in.

**Comment by BeardedBear** [comment]
I'm not sure I understand the problem, unless I've misunderstood, I can't reproduce the problem :/

**Comment by ptrwllrd** [comment]
Hello BearderBear! This seems to have been a quirk of VSCode addressed in the latest updates or something. I have just tried to reproduce the issue and the current file no longer loses the highlight. Thank you for you time! 🍯
