### ISSUE TITLE
HTML tags and text between are the same color - React / Gatsby 

### ISSUE THREAD

**Issue by K2adir** [BeardedBear/bearded-theme#37]
Could anyone tell me the location of the theme files, so I can change the color of the text within HTML tags? 
I really like the colors and readability however, text and HTML sharing the same color makes it difficult for me. 
I really like the black diamond but couldn't find its file in the "app" folder. 

<img width="414" alt="Screen Shot 2021-02-13 at 2 42 48 AM" src="https://user-images.githubusercontent.com/1120278/107833703-2b64f480-6da5-11eb-98d3-8d467cc14eff.png">

**Comment by BeardedBear** [comment]
I think you have a problem with your VSCode configuration, no problem for me : 
![image](https://user-images.githubusercontent.com/7188702/107834203-e1c0dd80-6d95-11eb-8016-e5ca7d7e44e3.png)

**Comment by K2adir** [comment]
Interesting.. I don't even know where to look or what to do in order to fix this error. Anyways, could you tell me the file location so, I could manually edit it?

**Comment by BeardedBear** [comment]
I don't think it's a good idea to modify the local files of the theme, they will be overwritten when a new version is released :) 

have you tried on a version of VSCode without other extensions than the theme ? (to determine if it would come from a conflict with another extension)

**Comment by K2adir** [comment]
got it! It is babel javascript by Michael McDermott changing it. 
thank you for fast response
