### ISSUE TITLE
Personally, I think comment color in light theme is too light to read 

### ISSUE THREAD

**Issue by WindSoilder** [BeardedBear/bearded-theme#38]
Firstly, let me thanks for your awesome theme!

I'm mostly using Solarized Light, however I find that the comment is hard to read clearly, this is my screenshot
![图片](https://user-images.githubusercontent.com/22256154/109605916-dc6add80-7b60-11eb-9327-b0db1c36cad5.png)

So I have to use a darker color for comment like this:
![图片](https://user-images.githubusercontent.com/22256154/109606050-0b814f00-7b61-11eb-96aa-e985807dd399.png)

If there are any chances to make comment easiler to read?

**Comment by WindSoilder** [comment]
Oh, here is my change, for now it works well for me:

```json
            "textMateRules": [
                {
                    "scope": [
                        "comment",
                        "string.quoted.docstring.multi",
                        "comment.block.documentation source"
                    ],
                    "settings": {
                        "foreground": "#989fb1", 
                    }
                }
            ]
```
Note that the comment color comes from another light theme: https://github.com/sdras/night-owl-vscode-theme/blob/main/themes/Night%20Owl-Light-color-theme.json#L228

**Comment by BeardedBear** [comment]
Hello, thanks for the feedback ! this will be fixedin the next version (within a few hours :))
