### ISSUE TITLE
Some colors in terminal don't looks fine

### ISSUE THREAD

**Issue by jgu7man** [BeardedBear/bearded-theme#39]
I love your theme
But there is something to be perfect for me
When I run terminal in VS Code I can't see some text I don't know how to fix it at least for me:
![image](https://user-images.githubusercontent.com/46007655/109815656-7ed4a080-7bf5-11eb-9827-f62205c3325f.png)

**Comment by BeardedBear** [comment]
Hello, thanks for the feedback ! this will be fixedin the next version (within a few hours :))
