### ISSUE TITLE
Data Types are not differentiated from normal text.

### ISSUE THREAD

**Issue by anshulxyz** [BeardedBear/bearded-theme#4]
In Python, I'd expect the words like `str`, `int`, `float` etc to look a little different than other colors. Or at least italicized. 

![Screenshot from 2019-09-15 11-13-10](https://user-images.githubusercontent.com/6121530/64917101-27950300-d7aa-11e9-8660-98994d0494ad.png)

Btw your Solarized theme is the best Solarized theme I've seen so far.

**Comment by BeardedBear** [comment]
Thank you very much! I fixed it locally, I'll push it now :)

**Comment by anshulxyz** [comment]
It works. Awesome.
