### ISSUE TITLE
odd color on git diff

### ISSUE THREAD

**Issue by MalcolmMielle** [BeardedBear/bearded-theme#42]
The color for the git diff as an odd underline on all lines in the blue theme:

![Screenshot 2021-04-19 150928](https://user-images.githubusercontent.com/4457840/115241672-624ae400-a121-11eb-900d-fd1eb8a0223e.png)

Would it be possible to remove it?

Also, comments are not very easy to read, I changed it to this color #727f8f which is just slightly lighter.

Thanks foir the great theme :)

**Comment by BeardedBear** [comment]
Done with 3.7.2 version ! Thanks ! :D
