### ISSUE TITLE
Python triple quotes not treated as comment but as string

### ISSUE THREAD

**Issue by camminady** [BeardedBear/bearded-theme#47]
Consider the following, simple python code
```python
def myfunc(x: int):
    """

    Parameters
    ----------
    x : int
        Something
    """

    s = "This is looking the way it should look"  # And here's a comment.
    print(s)
```

Regardless of the bearded-theme, the triple quotes are highlighted in the same way as strings are being highlighted. Here's a picture of what I see in VS code:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/24543638/118088135-e6158a80-b3c6-11eb-944d-e26d9c97b499.png">

I guess the triple quotes should be greyed out, just like the content of that docstring.

**Comment by BeardedBear** [comment]
Done ! Thanks !
