### ISSUE TITLE
Arc Blueberry Explorer too much contrast :enhancement:

### ISSUE THREAD

**Issue by andylacko** [BeardedBear/bearded-theme#49]
Hello, love this theme, but the contrast in the explorer is just little bit too much :) It is shinier than the code itself. If it would be little bit dimmer, I would definitely use this theme. Maybe to the level as the terminal color is right now. I would also make the terminal color little bit more darker, here is comparison to github theme

### BeardedBear
<img width="827" alt="image" src="https://user-images.githubusercontent.com/7139923/121506623-2b3bd500-c9e4-11eb-9ea3-03854879e3c9.png">

### Github Dark Default
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/7139923/121507199-b5843900-c9e4-11eb-8def-ce932f9ad9c3.png">

_Can I somewhere customize the colors little bit myself?_ 🤔
_I don't want to, I like things as they are, I want to edit only this one thing :)_

**Comment by BeardedBear** [comment]
For your information, I have pushed a new version that attenuates the color of the font of the sidebar elements, maybe that would be enough for you, but I would not change the background color of the sidebar, I like it like that!

But if you want to edit all this, I advise you to fork the repo and modify the values as you like, for that, you just need : 

1. Install the dependencies : 
```
yarn install
```


2. Launch the watcher : 
```
yarn watch
```

3. Launch the dev version with `F5` and edit variables

4. Compile the .vsix with 
```
yarn vcse package 
```

After that, you can install your version with add the package

The code needs some refactoring (especially the switch to Typescript), but it is still quite simple overall

**Comment by andylacko** [comment]
oh, thank you very much! didn't expected you to answer and fulfill my needs, just tried 🙂

thx for guide, how to customize, hope it will help someone, I am really glad that you created beautiful themes, if I would tweak myself, I wouldn't program anymore, just customizing my IDE so I don't want to fall into this pit 😄

🙌🏻🙌🏻🙌🏻
