### ISSUE TITLE
Too much colour in TypeScript

### ISSUE THREAD

**Issue by anshulxyz** [BeardedBear/bearded-theme#5]
In the case of TypeScript, the theme is colouring even the variables with the colour of referenced functions.

Check the Dracula for comparison.

![Screenshot from 2019-09-20 13-11-44](https://user-images.githubusercontent.com/6121530/65309005-dec5bb80-dba8-11e9-8b26-132b797c337f.png)

![Screenshot from 2019-09-20 13-11-44_edited](https://user-images.githubusercontent.com/6121530/65309017-e2f1d900-dba8-11e9-86c6-6a844e356a6a.png)

And now, how Dracula handles it:

![Screenshot from 2019-09-20 13-12-32](https://user-images.githubusercontent.com/6121530/65309065-fb61f380-dba8-11e9-81d2-af039fff1f69.png)

Ignore if this the feature you intentionally wanted.

**Comment by anshulxyz** [comment]
:thinking: maybe this is not really a legit issue

**Comment by BeardedBear** [comment]
it will be fixed in few days, in same time of your other issue, i haven't had much time available these days, it's a legit issue ! :)

**Comment by anshulxyz** [comment]
ah, take your time, man
no rush, didn't mean to mak haste :sweat_smile: 

:pray:
