### ISSUE TITLE
not available in the ext

### ISSUE THREAD

**Issue by Hkyx** [BeardedBear/bearded-theme#51]
Hi,

just tried to set the theme on a new install of vscode and it doesnt show the theme in the ext search. Same if I try dirctly the install command: ext install BeardedBear.beardedtheme

![image](https://user-images.githubusercontent.com/25575104/123480828-ebbedc80-d5d0-11eb-8d4c-fd32bf6977cd.png)

any  idea?

Thanks

**Comment by BeardedBear** [comment]
Strange 
![image](https://user-images.githubusercontent.com/7188702/123484262-593a2f80-d608-11eb-8613-291667c5a1f0.png)

But if i look your icons, i think you have an old version of VSCode, for exemple, my version is : 1.57.1

**Comment by Hkyx** [comment]
got the 1.56.2 don't think it come from that.

there is any way to install itd manually?

**Comment by Hkyx** [comment]
Solved, You're right about vscode version which needed the major update. installing manually the extension show me the compatibility error.
Due to be on Arch. I removed the major repo to visual-studio-code-bin  which was the latest
