### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by taernsietr** [BeardedBear/bearded-theme#52]
I'd like to know if it's possible for the extension to be published to Open VSX, which is an alternative registry (now hosted by Eclipse) from which users of non-Microsoft versions of Visual Code - such as Code OSS and vscodium - may install extensions per normal. The project has a page with instructions on publishing to their platform: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Alternatively, would permission be given for a third party to do so?

**Comment by BeardedBear** [comment]
Good point! I hadn't thought about it, I'll look at how to make my theme available on it, I'll look at it in a few days, I'm finishing the refactoring for version 4, this will be the opportunity! Thank you!

**Comment by BeardedBear** [comment]
@taernsietr Done ! https://open-vsx.org/extension/BeardedBear/beardedtheme

**Comment by taernsietr** [comment]
That was fast, hahah. Thanks a lot!
