### ISSUE TITLE
Issue in PHP where ?>

### ISSUE THREAD

**Issue by rarodja** [BeardedBear/bearded-theme#54]
in the PHP syntax when you close the brace in **?>** the question mark appears in a different color, I attach an example screenshot

![Example](https://user-images.githubusercontent.com/74628132/127679500-9f8a6bb0-1259-474e-ae85-f7145374f8d1.png)

**Comment by djmtype** [comment]
Actually, I'd like to piggyback off this issue. Some of php syntax highlighting on operators like equal signs and php statements appear very muted and blend in like comments. The same can be said for `*.blade.php` highlighting.
<img width="1712" alt="Screen Shot 2021-09-25 at 3 12 51 PM" src="https://user-images.githubusercontent.com/930713/134783720-4ea89eef-6d1b-423c-88b7-497031a5c151.png">

**Comment by rarodja** [comment]
Hello Scott! Thank you very much for the message, the problem is in the simple opening  <?php and closing ?> as an attachment in the capture, not in @php @endphp, it is only in basic php. Receives a warm greeting. Rafael. De: Scott RodEnviado: sábado, 25 de septiembre de 2021 21:17Para: BeardedBear/bearded-themeCC: rarodja; AuthorAsunto: Re: [BeardedBear/bearded-theme] Issue in PHP where ?> (#54) Actually, I'd like to piggyback off this issue. Some of php syntax highlighting on operators like equal signs and php statements appear very muted and blend in like comments. The same can be said for *.blade.php highlighting.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
