### ISSUE TITLE
Port theme for iTerm Color scheme

### ISSUE THREAD

**Issue by justisGipson** [BeardedBear/bearded-theme#58]
Could this be a thing some day? 

To be added to [iterm color schemes](https://iterm2colorschemes.com/)

**Comment by BeardedBear** [comment]
It is unlikely, at least directly by myself, I do not use Apple :)

**Comment by beardcoder** [comment]
You can use this cli tool to convert the themes :)
https://github.com/campvanilla/ditto

@justisGipson, if you want i can write you a script for this :)
