### ISSUE TITLE
Problem peek has unreadable colours.

### ISSUE THREAD

**Issue by anshulxyz** [BeardedBear/bearded-theme#6]
The languages which have linter support, once you over the issue there is an option to "peek" at the problem. All the themes under bearded-theme suite are unreadable for it.

I tested Golang and Python, same issue. I'm presuming it'll be the same for other languages.

Attaching some screenshots with the comparison with Dracula.

![Screenshot from 2019-09-26 02-17-04](https://user-images.githubusercontent.com/6121530/65638878-aab52500-e004-11e9-8217-7b1c460cbb2f.png)

![Screenshot from 2019-09-26 02-17-27](https://user-images.githubusercontent.com/6121530/65638855-a38e1700-e004-11e9-8bf1-1af0d19dff22.png)

![Peek 2019-09-26 02-25](https://user-images.githubusercontent.com/6121530/65639046-f7006500-e004-11e9-9000-e8ce8a3a0b6b.gif)

**Comment by BeardedBear** [comment]
Sorry for the reaction time, it's fixed!

**Comment by anshulxyz** [comment]
thank you
