### ISSUE TITLE
Question: what font type did you use in your pics?

### ISSUE THREAD

**Issue by AAkhilleus** [BeardedBear/bearded-theme#7]
I really like that font. Is it free? for Windows? where do I get it from? Thanks in advance

**Comment by BeardedBear** [comment]
Hey ! 

The font is : **Hasklug Nerd Font** ! It is a font derived from **Hasklig**, which is itself derived from **Source Code Pro**,  It adds ligatures and support for Powerline.

You can get it here : https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hasklig :)

**Comment by AAkhilleus** [comment]
Hi friend, that page has this [zip file](https://github.com/i-tu/Hasklig/releases/download/1.1/Hasklig-1.1.zip) only, and it contains _Hasklig*.otf_ files, I've installed those files in my Windows 10, and in the font viewer there is no _Hasklug Nerd Font_. In VSC, _settings.json_ file, I've added these lines:
```
	"editor.fontFamily": "Hasklig",
	"editor.fontLigatures": true,
```
But I don't see the change wished. I've found [this file](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Hasklig.zip) that contains  _Hasklug Nerd Font_ and other fonts. I've installed them, in VSC I have this configuration:
```
	"editor.fontFamily": "Hasklug Nerd Font",
	"editor.fontLigatures": true,
```
and same result. By way of confirming if we are talking about the same font, I'm requesting to you the font used for word _**function**_ in [this picture](https://raw.githubusercontent.com/BeardedBear/bearded-theme/master/assets/syntax-php.png) . Thanks in advance.

**Comment by BeardedBear** [comment]
Try `"editor.fontFamily": "Hasklug Nerd Font Medium",` and restart VS Code, VS Code doesn't work with fresh installation of font, he need to be restarted to suport new installed fonts ^^

**Comment by AAkhilleus** [comment]
No luck 😢 . I show my current state with pics in [this folder](https://drive.google.com/open?id=1BIpoy9Bbu6gS14oDZFp5wlRClkG2esqY)

**Comment by AAkhilleus** [comment]
Dude, I think that "Hasklug Nerd Font Medium" is not correct, it is another font like [FiraFlott](https://github.com/kosimst/FiraFlott) or [Firicico](https://github.com/kosimst/Firicico). And it requires additional configuration. Thanks anyway.
