### ISSUE TITLE
Inconsistencies with syntax color

### ISSUE THREAD

**Issue by Raj2032** [BeardedBear/bearded-theme#76]
While this is an extremly stunning looking theme and the colors sytnax look amazing I wanted to report on color syntax inconsistencies. I am using hte ociean theme.

I am using Rust and I made an example code:

![image](https://user-images.githubusercontent.com/29293830/165266417-59d23177-6022-4abe-ad14-63487c123ff8.png)

Inside the `main()` function, how come all the variables are red colored, but inside `struct` `Rect`, the `x` and `y` are not colored at all?

And inside the `impl` `Rect`, inside the method `square(side: u32)`, why is it that the `side` variable is pink?

and inside the `Self{}`, how come the variables `x` and `y` is now orange?

Another issue I wanted to report is this line here:

`let square = Rect::square(50u32);` When I am passing in `50u32` how come the `u32` is not purple?

**Comment by BeardedBear** [comment]
what version of my theme do you have installed? I think I see that you are not up to date.

when i rewrite your code i don't have the same result as you, but as i don't know anything about Rust, i don't know your setup, what extensions are needed to have the right syntax support, what are yours?

**Comment by Raj2032** [comment]
@BeardedBear Hey man, I realised what was going on, I am using `rust-analyzer` which is a Rust extension which changes colors around, when I disable the extension then the colors are normal.
