### ISSUE TITLE
RE: Licensing

### ISSUE THREAD

**Issue by rustylabs** [BeardedBear/bearded-theme#78]
Hi there, I decided to fork one of your themes `bearded-theme-oceanic` into my github repo:

https://github.com/rustylabs/darkpotion

I have provided credits to your repo in the `README.md`.

Please let me know if I am not violating any copyright protection before I distribute it to the marketplace?

**Comment by BeardedBear** [comment]
Hi ! As long as my project is credited, no worries, go!

**Comment by rustylabs** [comment]
Thanks mate its been credited your project and its now live.
________________________________

**Comment by deccer** [comment]
Quite weird to ask for credits when you don't credit any of the color schemes, at all : )
