### ISSUE TITLE
Chained token colors

### ISSUE THREAD

**Issue by TheJedinator** [BeardedBear/bearded-theme#8]
First of all I want to say I really enjoy the theme! 

Currently I find it difficult to use with JS. Simply due to having chained tokens being the same color. 

For example if I have Object.Attribute.attribute. all three of these will be the same pinkish color. or even just having Object.attribute both be the same is difficult to read. making a single line comparing nested properties a little hellish. 

I have tried to read the VS code documentation relating to this to see if I could fix it and offer a PR alas I cannot find where these keywords would be.

**Comment by BeardedBear** [comment]
I think that with the last update, this problem is solved :)
