### ISSUE TITLE
Fonts on themes

### ISSUE THREAD

**Issue by MomoCeres** [BeardedBear/bearded-theme#84]
I really love the Monokai Black theme that you have. Is it possible to have this type of font setting for the theme? With the "class", "def" italics as well? 

![image](https://user-images.githubusercontent.com/16159664/180490408-2d74900a-a4fe-446a-961b-7305b04ba377.png)

**Comment by BeardedBear** [comment]
What you can do is to override the theme in your configuration file, using the custom selectors, and passing them the italic argument. for doing that, i give you links for doing it yourself 
- https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
- https://code.visualstudio.com/api/references/theme-color

and for know wich element add to customized your version, you can use the integrated tool in VSCode, by pressing `ctrl/cmd + shift + P` and select `inspect editor tokens ans scopes`
