### ISSUE TITLE
feat: Add support for ".patch" and ".diff" files

### ISSUE THREAD

**Issue by tyler36** [BeardedBear/bearded-theme#90]
## Feature Request
Would it be possible to add support for `.patch` and `.diff` files?

I've been a long term user of "Fresh Material" theme and recently started using "Beared Themes: Molokai Stone"

"Beared Themes: Molokai Stone"
![molokai-stone](https://user-images.githubusercontent.com/7234392/194233886-2825d4c5-abe6-4b21-ae82-c58fff60edd8.png)

"Fresh Material: Indigo"
![freshMaterial-indigo](https://user-images.githubusercontent.com/7234392/194233900-33d0a98b-0fde-4745-a085-47739ffb9ba9.png)

I've been working with recently and syntax highlight makes it really easy to see what's been added / removed.

**Comment by BeardedBear** [comment]
Thanks, Done !

**Comment by tyler36** [comment]
Confirmed. 

`patch` files now show 
- green for additions
- red for deleted
- `@` orange for index markers.


Thank you!
