### ISSUE TITLE
GraphQL resolvers are using the same icon as general TS files

### ISSUE THREAD

**Issue by DenisLutsky** [BeardedBear/bearded-theme#93]
how it looks
![image](https://user-images.githubusercontent.com/116076603/196931604-a5452d5a-fc44-407c-b131-96ea68a0f807.png)

expected
![image](https://user-images.githubusercontent.com/116076603/196931912-52fb2835-4a62-4746-aa70-18e817daceb6.png)

**Comment by BeardedBear** [comment]
I redirect this issue to the right repository : https://github.com/BeardedBear/bearded-icons/issues/95
